---
language: python
python: "2.7"

install: pip install ansible
install: pip install ansible-lint
install: pip install yamllint

script: ansible-playbook ansible-lint ./
script: ansible-playbook yamllint ./
