---
- name: Use group to create nginx-exp system group
  become: true
  group:
    name: nginx-exp
    system: yes
    state: present
- name: Create nginx-exp system user, member of nginx-exp group
  become: true
  user:
    name: nginx-exp
    group: nginx-exp
    system: yes
    state: present
- name: Use get_url to download nginx-exporter
  get_url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.3.0/nginx-prometheus-exporter-0.3.0-linux-amd64.tar.gz
  dest: ~/Downloads/nginx-prometheus-exporter-0.3.0-linux-amd64.tar.gz
- name: Use unarchive to unpack the downloaded exporter
  unarchive: 
    src: ~/Downloads/nginx-prometheus-exporter-0.3.0-linux-amd64.tar.gz
    dest: ~/Downloads/
- name: Use template to create /etc/systemd/system/nginx_exporter.service file
  template:
    src: /templates/nginx_exporter.service
    dest: /etc/systemd/system/nginx_exporter.service
- name: Use systemd to start and enable the nginx_exporter service.
  systemd:
    name: nginx_exporter
    state: started
    enabled: yes
    