---
- name: Use group to create nginx-exp system group
  become: true
  group:
    name: nginx-exp
    state: present
    system: true
- name: Use user to create nginx-exp system user, a member of nginx-exp group
  become: true
  user:
    name: nginx-exp
    system: true
    state: present
    group: nginx-exp
- name: Use get_url to download nginx-exporter
  become: true
  get_url: 'https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.3.0/nginx-prometheus-exporter-0.3.0-linux-amd64.tar.gz'
  dest: '~/Downloads/nginx-prometheus-exporter-0.3.0-linux-amd64.tar.gz'
- name: Use unarchive to unpack the downloaded exporter
  become: true
  unarchive:
    src: '~/Downloads/nginx-prometheus-exporter-0.3.0-linux-amd64.tar.gz'
    dest: '~/Downloads/nginx-prometheus-exporter-0.3.0-linux-amd64/'
- name: Use template to create /etc/systemd/system/nginx_exporter.service file
  become: true
  template:
    src: template/nginx_exporter.service
    dest: /etc/systemd/system/nginx_exporter.service
- name: Use systemd to start and enable the nginx_exporter service.
  become: true
  systemd:
    state: started
    name: nginx_exporter
    enabled: true
- name: fail playbook when GET request to port 9113 metrics does not return nginx_up 1
  uri:
    url: http://localhost:9113/metrics
    return_content: true
    register: nginx_up
    method: GET
  fail:
    msg: 'port 9113/metrics does not return nginx_up 1'
  when: "'nginx_up 1' not in nginx_up.content"
- name: Use uri to fail playbook when GET request to port 80 does not return status code 200.
  uri:
    url: http://localhost:80
